name: PRs

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup Node
        uses: setup-node@v4.4.0
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Lint
        run: npm run lint
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

  deploy:
    name: Create preview deployment
    permissions:
      # issues and pull-requests write permissions are required for creating comments
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@45dc7a8a626b375bdbdabbc0b56ceb28e81b239d #v6.0.1
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ github.head_ref }}
          database: ${{ secrets.NEON_DATABASE_NAME }}
          role: ${{ secrets.NEON_DATABASE_USERNAME }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Setup Node
        uses: setup-node@v4.4
        with:
          node-version-file: 'package.json'
          cache: npm

      # - name: Compute Fixed Deployment URL
      #   run: |
      #     URL=$(echo "${{ github.head_ref }}" | sed 's/[^a-zA-Z0-9]/-/g')
      #     URL=$(echo ${URL:0:30} | sed 's/-*$//')  # Remove trailing hyphens
      #     URL=$URL.domain.com
      #     echo "fixed_preview_url=$URL" >> $GITHUB_ENV

      - name: Deploy to Vercel
        run: |
          chmod +x .github/workflows/scripts/build-and-deploy.sh
          .github/workflows/scripts/build-and-deploy.sh \
            --environment "preview" \
            --branch "${{ github.head_ref }}" \
            --token "${{ secrets.VERCEL_TOKEN }}" \
            --database "${{ steps.create-branch.outputs.db_url_pooled }}" \
            --org-id "${{ vars.VERCEL_ORG_ID }}" \
            --project-id "${{ vars.VERCEL_PROJECT_ID }}" \
            --pr-number "${{ github.event.number }}"

      # - name: Setup Fixed Deployment URL
      #   run:
      #     npm vercel alias set ${{ env.preview_url }} ${{ env.fixed_preview_url
      #     }} --scope=<scope> --token=${{ secrets.VERCEL_TOKEN }}

      - name: Find Existing Comment
        id: find-comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e #v3.1.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Vercel Preview URL'

      - name: Comment on Pull Request
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 #v4.0.0
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <details>
            <summary>
              <a href="https://${{ env.preview_url }}">
                :rocket: Vercel Preview URL
              </a>
            </summary>
            <ul>
              <li>:rocket: https://${{ env.preview_url }}</li>
              <li><a href="https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}">:elephant: Neon branch</a></li>
            </ul>
            </details>
